export const PRIORITY_CATEGORIES = [
  {
    category: "inventor",
    target: 500,
    topics: [
      "Black inventors 19th century",
      "African American patents",
      "Black women inventors",
      "HBCU research innovations",
      "Black scientists inventions",
      "Indigenous American inventors",
    ],
  },
  {
    category: "business",
    target: 1000,
    topics: [
      "Black Wall Street entrepreneurs",
      "African American business owners history",
      "Black women CEOs",
      "HBCU alumni entrepreneurs",
      "Black tech founders",
      "Indigenous business leaders",
      "Caribbean entrepreneurs diaspora",
    ],
  },
  {
    category: "media",
    target: 500,
    topics: [
      "Black newspaper publishers",
      "African American journalists history",
      "Black radio pioneers",
      "Black television history",
      "Hip-hop media founders",
      "Black podcast pioneers",
      "African American film studios",
    ],
  },
  {
    category: "politician",
    target: 800,
    topics: [
      "African American mayors history",
      "Black congresspeople 20th century",
      "First Black elected officials by state",
      "HBCU alumni politicians",
      "Black women in politics",
      "Indigenous American elected officials",
    ],
  },
  {
    category: "educator",
    target: 600,
    topics: [
      "HBCU founders and presidents",
      "Black educators Reconstruction era",
      "African American teachers civil rights",
      "Black university presidents",
      "Indigenous education advocates",
    ],
  },
  {
    category: "athlete",
    subcategoryFocus: "pioneer",
    target: 500,
    topics: [
      "First Black athletes by sport",
      "Jackie Robinson contemporaries",
      "Black Olympic athletes history",
      "HBCU sports legends",
      "Indigenous athletes history",
    ],
  },
  {
    category: "regional",
    target: 200,
    topics: [
      "Black communities Great Plains",
      "Indigenous nations Pacific Northwest",
      "Black cowboys American West",
      "Freedmen towns Oklahoma",
      "Black Appalachian communities",
      "Caribbean diaspora New York",
      "African American communities Pacific Islands",
      "Indigenous nations Great Lakes",
      "Black community Alaska",
      "Afro-Latino communities Southwest",
    ],
  },
]

export const CULTURAL_RELEVANCE_KEYWORDS = [
  "African American",
  "Black",
  "Indigenous",
  "Native American",
  "Caribbean",
  "HBCU",
  "diaspora",
  "Afro-Latino",
  "Afro-Caribbean",
  "African diaspora",
  "First Nations",
  "tribal",
  "freedmen",
  "Reconstruction",
  "civil rights",
  "Gullah",
  "Creole",
  "Harlem",
  "historically Black",
]
