import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useLanguage } from './LanguageProvider';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card, CardContent } from '@/components/ui/card';
import { 
  Image, 
  Download, 
  RefreshCw, 
  Share2, 
  Wand2, 
  User, 
  Briefcase, 
  Home, 
  Palette,
  Mic
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface GeneratedImage {
  id: number;
  prompt: string;
  imageUrl: string;
  createdAt: string;
}

interface ImageGeneratorProps {
  userId: number;
}

const presetPrompts = {
  portrait: "Professional headshot of a confident person, studio lighting, high quality",
  business: "Modern business professional in corporate setting, clean background",
  lifestyle: "Casual lifestyle photo, natural lighting, authentic moment",
  creative: "Artistic and creative composition, vibrant colors, unique perspective"
};

export function ImageGenerator({ userId }: ImageGeneratorProps) {
  const [prompt, setPrompt] = useState('');
  const [currentImage, setCurrentImage] = useState<string | null>(null);
  const { language, t } = useLanguage();
  const { toast } = useToast();

  // Fetch generated images
  const { data: images = [] } = useQuery({
    queryKey: ['/api/images', userId],
    enabled: !!userId,
  });

  // Generate image mutation
  const generateImageMutation = useMutation({
    mutationFn: async (imageData: { userId: number; prompt: string; language: string }) => {
      const response = await apiRequest('POST', '/api/images/generate', imageData);
      return response.json();
    },
    onSuccess: (data) => {
      setCurrentImage(data.imageUrl);
      setPrompt('');
      toast({
        title: "Success",
        description: "Image generated successfully!",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to generate image. Please try again.",
        variant: "destructive",
      });
    },
  });

  const handleGenerateImage = () => {
    if (!prompt.trim()) return;

    generateImageMutation.mutate({
      userId,
      prompt: prompt.trim(),
      language,
    });
  };

  const handlePresetClick = (presetKey: keyof typeof presetPrompts) => {
    setPrompt(presetPrompts[presetKey]);
  };

  const handleSurpriseMe = () => {
    const surprisePrompts = [
      "A magical forest with glowing mushrooms and fairy lights",
      "Futuristic cityscape at sunset with flying cars",
      "Cozy coffee shop on a rainy day, warm lighting",
      "Majestic mountain landscape with aurora borealis",
      "Underwater coral reef with tropical fish",
      "Steampunk robot in a Victorian library"
    ];
    const randomPrompt = surprisePrompts[Math.floor(Math.random() * surprisePrompts.length)];
    setPrompt(randomPrompt);
  };

  const downloadImage = async (imageUrl: string) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `bonita-generated-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({
        title: "Success",
        description: "Image downloaded successfully!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to download image.",
        variant: "destructive",
      });
    }
  };

  const shareImage = async (imageUrl: string) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Generated by Bonita AI',
          url: imageUrl,
        });
      } catch (error) {
        // Fallback to clipboard
        navigator.clipboard.writeText(imageUrl);
        toast({
          title: "Success",
          description: "Image URL copied to clipboard!",
        });
      }
    } else {
      navigator.clipboard.writeText(imageUrl);
      toast({
        title: "Success",
        description: "Image URL copied to clipboard!",
      });
    }
  };

  return (
    <div className="flex-1 flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border bg-background">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold">{t('imageHeader')}</h2>
            <p className="text-muted-foreground">{t('imageSubtitle')}</p>
          </div>
          <Button variant="outline" onClick={handleSurpriseMe}>
            <Wand2 className="mr-2 h-4 w-4" />
            {t('surpriseMe')}
          </Button>
        </div>
      </div>

      <ScrollArea className="flex-1 p-6">
        <div className="max-w-4xl mx-auto">
          {/* Preset Prompts */}
          <div className="mb-8">
            <h3 className="text-lg font-semibold mb-4">{t('quickPresets')}</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <Button
                variant="outline"
                className="p-4 h-auto flex flex-col items-center space-y-2"
                onClick={() => handlePresetClick('portrait')}
              >
                <User className="h-6 w-6" />
                <span className="text-sm font-medium">{t('portrait')}</span>
              </Button>
              <Button
                variant="outline"
                className="p-4 h-auto flex flex-col items-center space-y-2"
                onClick={() => handlePresetClick('business')}
              >
                <Briefcase className="h-6 w-6" />
                <span className="text-sm font-medium">{t('business')}</span>
              </Button>
              <Button
                variant="outline"
                className="p-4 h-auto flex flex-col items-center space-y-2"
                onClick={() => handlePresetClick('lifestyle')}
              >
                <Home className="h-6 w-6" />
                <span className="text-sm font-medium">{t('lifestyle')}</span>
              </Button>
              <Button
                variant="outline"
                className="p-4 h-auto flex flex-col items-center space-y-2"
                onClick={() => handlePresetClick('creative')}
              >
                <Palette className="h-6 w-6" />
                <span className="text-sm font-medium">{t('creative')}</span>
              </Button>
            </div>
          </div>

          {/* Generated Image Display */}
          <div className="mb-8">
            <Card>
              <CardContent className="p-8 text-center">
                {currentImage ? (
                  <>
                    <img 
                      src={currentImage} 
                      alt="Generated Image" 
                      className="mx-auto rounded-xl shadow-lg max-w-full h-auto mb-4"
                    />
                    <div className="flex justify-center space-x-3">
                      <Button onClick={() => downloadImage(currentImage)}>
                        <Download className="mr-2 h-4 w-4" />
                        {t('download')}
                      </Button>
                      <Button variant="outline" onClick={() => handleGenerateImage()}>
                        <RefreshCw className="mr-2 h-4 w-4" />
                        {t('remix')}
                      </Button>
                      <Button variant="outline" onClick={() => shareImage(currentImage)}>
                        <Share2 className="mr-2 h-4 w-4" />
                        {t('share')}
                      </Button>
                    </div>
                  </>
                ) : (
                  <div className="py-16">
                    <Image className="mx-auto h-16 w-16 text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">
                      {generateImageMutation.isPending 
                        ? "Generating your image..." 
                        : "Your generated image will appear here"}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Prompt Input */}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">
                {t('describeImage')}
              </label>
              <Textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="A beautiful sunset over the city skyline with warm golden light..."
                rows={3}
                className="resize-none"
              />
            </div>
            
            <div className="flex space-x-3">
              <Button 
                onClick={handleGenerateImage}
                disabled={!prompt.trim() || generateImageMutation.isPending}
                className="flex-1"
              >
                {generateImageMutation.isPending ? (
                  <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Image className="mr-2 h-4 w-4" />
                )}
                {t('generateImage')}
              </Button>
              <Button size="icon" variant="outline">
                <Mic className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
