import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useLanguage } from './LanguageProvider';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

import { Card, CardContent } from '@/components/ui/card';
import { 
  Image, 
  Download, 
  RefreshCw, 
  Share2, 
  Wand2, 
  User, 
  Briefcase, 
  Home, 
  Palette,
  Mic
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface GeneratedImage {
  id: number;
  prompt: string;
  imageUrl: string;
  createdAt: string;
}

interface ImageGeneratorProps {
  userId: number;
}

const presetPrompts = {
  portrait: "Professional headshot of a confident person, studio lighting, high quality",
  business: "Modern business professional in corporate setting, clean background",
  lifestyle: "Casual lifestyle photo, natural lighting, authentic moment",
  creative: "Artistic and creative composition, vibrant colors, unique perspective"
};

export function ImageGenerator({ userId }: ImageGeneratorProps) {
  const [prompt, setPrompt] = useState('');
  const [currentImage, setCurrentImage] = useState<string | null>(null);
  const { language, t } = useLanguage();
  const { toast } = useToast();

  // Fetch generated images
  const { data: images = [] } = useQuery({
    queryKey: ['/api/images'],
    enabled: !!userId,
  });

  // Generate image mutation
  const queryClient = useQueryClient();
  
  const generateImageMutation = useMutation({
    mutationFn: async (imageData: { userId: number; prompt: string; language: string }) => {
      const response = await apiRequest('POST', '/api/images/generate', imageData);
      return response.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['/api/images'] });
      queryClient.invalidateQueries({ queryKey: [`/api/user/${userId}`] });
      
      if (data && data.imageUrl) {
        setCurrentImage(data.imageUrl);
        toast({
          title: "Image Generated!",
          description: "Your image is ready!",
        });
      }
      setPrompt('');
    },
    onError: (error: any) => {
      console.error('Image generation error:', error);
      toast({
        title: "Error",
        description: error?.message || "Failed to generate image. Please try again.",
        variant: "destructive",
      });
    },
  });

  const handleGenerateImage = () => {
    if (!prompt.trim()) return;

    generateImageMutation.mutate({
      userId,
      prompt: prompt.trim(),
      language,
    });
  };

  const handlePresetClick = (presetKey: keyof typeof presetPrompts) => {
    setPrompt(presetPrompts[presetKey]);
  };

  const handleSurpriseMe = () => {
    const surprisePrompts = [
      "A magical forest with glowing mushrooms and fairy lights",
      "Futuristic cityscape at sunset with flying cars",
      "Cozy coffee shop on a rainy day, warm lighting",
      "Majestic mountain landscape with aurora borealis",
      "Underwater coral reef with tropical fish",
      "Steampunk robot in a Victorian library"
    ];
    const randomPrompt = surprisePrompts[Math.floor(Math.random() * surprisePrompts.length)];
    setPrompt(randomPrompt);
  };

  const downloadImage = async (imageUrl: string) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `bonita-generated-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      
      toast({
        title: "Success",
        description: "Image downloaded successfully!",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to download image.",
        variant: "destructive",
      });
    }
  };

  const shareImage = async (imageUrl: string) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Generated by Bonita AI',
          url: imageUrl,
        });
      } catch (error) {
        // Fallback to clipboard
        navigator.clipboard.writeText(imageUrl);
        toast({
          title: "Success",
          description: "Image URL copied to clipboard!",
        });
      }
    } else {
      navigator.clipboard.writeText(imageUrl);
      toast({
        title: "Success",
        description: "Image URL copied to clipboard!",
      });
    }
  };

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="p-6 border-b border-border bg-background flex-shrink-0">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold">{t('imageHeader')}</h2>
            <p className="text-muted-foreground">{t('imageSubtitle')}</p>
          </div>
          <Button variant="outline" onClick={handleSurpriseMe}>
            <Wand2 className="mr-2 h-4 w-4" />
            {t('surpriseMe')}
          </Button>
        </div>
      </div>

      {/* Scrollable Content */}
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-4xl mx-auto p-6">
          {/* Preset Prompts */}
          <div className="mb-8">
            <h3 className="text-lg font-semibold mb-4">{t('quickPresets')}</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div
                className="p-4 border-2 border-border rounded-lg cursor-pointer hover:border-primary hover:bg-primary/5 transition-all duration-200 flex flex-col items-center space-y-2"
                onClick={() => {
                  console.log('Portrait preset clicked');
                  handlePresetClick('portrait');
                  toast({
                    title: "Preset Selected",
                    description: "Portrait preset loaded!",
                  });
                }}
              >
                <User className="h-6 w-6" />
                <span className="text-sm font-medium">{t('portrait')}</span>
              </div>
              <div
                className="p-4 border-2 border-border rounded-lg cursor-pointer hover:border-primary hover:bg-primary/5 transition-all duration-200 flex flex-col items-center space-y-2"
                onClick={() => {
                  console.log('Business preset clicked');
                  handlePresetClick('business');
                  toast({
                    title: "Preset Selected",
                    description: "Business preset loaded!",
                  });
                }}
              >
                <Briefcase className="h-6 w-6" />
                <span className="text-sm font-medium">{t('business')}</span>
              </div>
              <div
                className="p-4 border-2 border-border rounded-lg cursor-pointer hover:border-primary hover:bg-primary/5 transition-all duration-200 flex flex-col items-center space-y-2"
                onClick={() => {
                  console.log('Lifestyle preset clicked');
                  handlePresetClick('lifestyle');
                  toast({
                    title: "Preset Selected",
                    description: "Lifestyle preset loaded!",
                  });
                }}
              >
                <Home className="h-6 w-6" />
                <span className="text-sm font-medium">{t('lifestyle')}</span>
              </div>
              <div
                className="p-4 border-2 border-border rounded-lg cursor-pointer hover:border-primary hover:bg-primary/5 transition-all duration-200 flex flex-col items-center space-y-2"
                onClick={() => {
                  console.log('Creative preset clicked');
                  handlePresetClick('creative');
                  toast({
                    title: "Preset Selected",
                    description: "Creative preset loaded!",
                  });
                }}
              >
                <Palette className="h-6 w-6" />
                <span className="text-sm font-medium">{t('creative')}</span>
              </div>
            </div>
          </div>

          {/* Generated Image Display */}
          <div className="mb-8">
            <Card>
              <CardContent className="p-8 text-center">
                {currentImage ? (
                  <>
                    <img 
                      src={currentImage} 
                      alt="Generated Image" 
                      className="mx-auto rounded-xl shadow-lg max-w-full h-auto mb-4"
                    />
                    <div className="flex justify-center space-x-3">
                      <Button onClick={() => downloadImage(currentImage)}>
                        <Download className="mr-2 h-4 w-4" />
                        {t('download')}
                      </Button>
                      <Button variant="outline" onClick={() => handleGenerateImage()}>
                        <RefreshCw className="mr-2 h-4 w-4" />
                        {t('remix')}
                      </Button>
                      <Button variant="outline" onClick={() => shareImage(currentImage)}>
                        <Share2 className="mr-2 h-4 w-4" />
                        {t('share')}
                      </Button>
                    </div>
                  </>
                ) : (
                  <div className="py-16">
                    <Image className="mx-auto h-16 w-16 text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">
                      {generateImageMutation.isPending 
                        ? "Generating your image..." 
                        : "Your generated image will appear here"}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Prompt Input */}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">
                {t('describeImage')}
              </label>
              <Textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="A beautiful sunset over the city skyline with warm golden light..."
                rows={3}
                className="resize-none"
              />
            </div>
            
            <div className="flex space-x-3">
              <Button 
                onClick={handleGenerateImage}
                disabled={!prompt.trim() || generateImageMutation.isPending}
                className="flex-1"
              >
                {generateImageMutation.isPending ? (
                  <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Image className="mr-2 h-4 w-4" />
                )}
                {t('generateImage')}
              </Button>
              <Button size="icon" variant="outline">
                <Mic className="h-4 w-4" />
              </Button>
            </div>
          </div>

          {/* Images Created Section */}
          {images.length > 0 && (
            <div className="mt-8">
              <h3 className="text-lg font-semibold mb-4">Images Created</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {images.slice(0, 9).map((image: GeneratedImage) => (
                  <Card key={image.id} className="overflow-hidden hover:shadow-lg transition-shadow">
                    <div className="aspect-square relative">
                      <img 
                        src={image.imageUrl} 
                        alt={image.prompt}
                        className="w-full h-full object-cover cursor-pointer"
                        onClick={() => setCurrentImage(image.imageUrl)}
                      />
                      <div className="absolute top-2 right-2 opacity-0 hover:opacity-100 transition-opacity">
                        <div className="flex space-x-1">
                          <Button
                            size="sm"
                            variant="secondary"
                            className="h-8 w-8 p-0"
                            onClick={(e) => {
                              e.stopPropagation();
                              downloadImage(image.imageUrl);
                            }}
                          >
                            <Download className="h-3 w-3" />
                          </Button>
                          <Button
                            size="sm"
                            variant="secondary"
                            className="h-8 w-8 p-0"
                            onClick={(e) => {
                              e.stopPropagation();
                              shareImage(image.imageUrl);
                            }}
                          >
                            <Share2 className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>
                    </div>
                    <CardContent className="p-4">
                      <p className="text-sm text-muted-foreground line-clamp-2">
                        {image.prompt}
                      </p>
                      <p className="text-xs text-muted-foreground mt-2">
                        {new Date(image.createdAt).toLocaleDateString()}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
